/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Inheritance.Film;
import SystemAndMain.CollectiblesSys;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Ali and yusuf
 */
public class addFilm extends javax.swing.JFrame {

    /**
     * Creates new form addFilm
     */
    public addFilm() {
        initComponents();
        setSize(900, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        labelPublisher = new javax.swing.JLabel();
        textPublisher = new javax.swing.JTextField();
        labelCondition = new javax.swing.JLabel();
        comboCondition = new javax.swing.JComboBox<>();
        labelYear = new javax.swing.JLabel();
        textYear = new javax.swing.JTextField();
        labelTitle = new javax.swing.JLabel();
        textTitle = new javax.swing.JTextField();
        labelPrice = new javax.swing.JLabel();
        textDirector = new javax.swing.JTextField();
        labelGenre = new javax.swing.JLabel();
        comboGenre = new javax.swing.JComboBox<>();
        textPrice = new javax.swing.JTextField();
        radioDvd = new javax.swing.JRadioButton();
        radioBLuray = new javax.swing.JRadioButton();
        radio4k = new javax.swing.JRadioButton();
        label4K = new javax.swing.JLabel();
        labelDvd = new javax.swing.JLabel();
        labelBluRay = new javax.swing.JLabel();
        labelDirector1 = new javax.swing.JLabel();
        boxSteelCase = new javax.swing.JCheckBox();
        addButton = new javax.swing.JPanel();
        labelAdd = new javax.swing.JLabel();
        textInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(920, 500));

        background.setBackground(new java.awt.Color(37, 36, 35));
        background.setPreferredSize(new java.awt.Dimension(1500, 1500));

        labelPublisher.setBackground(new java.awt.Color(255, 255, 255));
        labelPublisher.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelPublisher.setForeground(new java.awt.Color(255, 255, 255));
        labelPublisher.setText("Publisher:");

        textPublisher.setBackground(new java.awt.Color(60, 63, 66));
        textPublisher.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textPublisher.setForeground(new java.awt.Color(255, 255, 255));
        textPublisher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 66), 2));
        textPublisher.setCaretColor(new java.awt.Color(202, 80, 16));
        textPublisher.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPublisherActionPerformed(evt);
            }
        });

        labelCondition.setBackground(new java.awt.Color(255, 255, 255));
        labelCondition.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelCondition.setForeground(new java.awt.Color(255, 255, 255));
        labelCondition.setText("Condition:");

        comboCondition.setBackground(new java.awt.Color(255, 102, 51));
        comboCondition.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboCondition.setForeground(new java.awt.Color(0, 0, 0));
        comboCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Near Mint", "Fine", "Good", "Fair", "Poor" }));

        labelYear.setBackground(new java.awt.Color(255, 255, 255));
        labelYear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelYear.setForeground(new java.awt.Color(255, 255, 255));
        labelYear.setText("Year:");

        textYear.setBackground(new java.awt.Color(60, 63, 66));
        textYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textYear.setForeground(new java.awt.Color(255, 255, 255));
        textYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 66), 2));
        textYear.setCaretColor(new java.awt.Color(202, 80, 16));
        textYear.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textYearActionPerformed(evt);
            }
        });

        labelTitle.setBackground(new java.awt.Color(255, 255, 255));
        labelTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("Title:");

        textTitle.setBackground(new java.awt.Color(60, 63, 66));
        textTitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textTitle.setForeground(new java.awt.Color(255, 255, 255));
        textTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 66), 2));
        textTitle.setCaretColor(new java.awt.Color(202, 80, 16));
        textTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTitleActionPerformed(evt);
            }
        });

        labelPrice.setBackground(new java.awt.Color(255, 255, 255));
        labelPrice.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelPrice.setForeground(new java.awt.Color(255, 255, 255));
        labelPrice.setText("Price:");

        textDirector.setBackground(new java.awt.Color(60, 63, 66));
        textDirector.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textDirector.setForeground(new java.awt.Color(255, 255, 255));
        textDirector.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 66), 2));
        textDirector.setCaretColor(new java.awt.Color(202, 80, 16));
        textDirector.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDirectorActionPerformed(evt);
            }
        });

        labelGenre.setBackground(new java.awt.Color(255, 255, 255));
        labelGenre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelGenre.setForeground(new java.awt.Color(255, 255, 255));
        labelGenre.setText("Genre:");

        comboGenre.setBackground(new java.awt.Color(0, 0, 0));
        comboGenre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboGenre.setForeground(new java.awt.Color(0, 0, 0));
        comboGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Comedy", "Drama", "Fantasy", "Horror", "Mystery", "Romance", "Thriller", "Western" }));

        textPrice.setBackground(new java.awt.Color(60, 63, 66));
        textPrice.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textPrice.setForeground(new java.awt.Color(255, 255, 255));
        textPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 66), 2));
        textPrice.setCaretColor(new java.awt.Color(202, 80, 16));
        textPrice.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPriceActionPerformed(evt);
            }
        });

        radioDvd.setBackground(new java.awt.Color(37, 36, 35));
        buttonGroup.add(radioDvd);
        radioDvd.setForeground(new java.awt.Color(37, 36, 35));
        radioDvd.setText("DVD");

        radioBLuray.setBackground(new java.awt.Color(37, 36, 35));
        buttonGroup.add(radioBLuray);
        radioBLuray.setForeground(new java.awt.Color(37, 36, 35));
        radioBLuray.setText("Blu-ray");

        radio4k.setBackground(new java.awt.Color(37, 36, 35));
        buttonGroup.add(radio4k);
        radio4k.setForeground(new java.awt.Color(37, 36, 35));
        radio4k.setText("4K");

        label4K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_4k_50px.png"))); // NOI18N

        labelDvd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_dvd_logo_50px.png"))); // NOI18N

        labelBluRay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_blu-ray_50px.png"))); // NOI18N

        labelDirector1.setBackground(new java.awt.Color(255, 255, 255));
        labelDirector1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelDirector1.setForeground(new java.awt.Color(255, 255, 255));
        labelDirector1.setText("Director:");

        boxSteelCase.setBackground(new java.awt.Color(37, 36, 35));
        boxSteelCase.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxSteelCase.setForeground(new java.awt.Color(255, 255, 255));
        boxSteelCase.setText("Steel Case");

        addButton.setBackground(new java.awt.Color(60, 63, 66));
        addButton.setForeground(new java.awt.Color(60, 63, 66));
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addButtonMouseReleased(evt);
            }
        });

        labelAdd.setBackground(new java.awt.Color(153, 255, 51));
        labelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_to_collection_96px.png"))); // NOI18N

        javax.swing.GroupLayout addButtonLayout = new javax.swing.GroupLayout(addButton);
        addButton.setLayout(addButtonLayout);
        addButtonLayout.setHorizontalGroup(
            addButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addButtonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelAdd)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        addButtonLayout.setVerticalGroup(
            addButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelAdd)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        textInfo.setBackground(new java.awt.Color(255, 255, 255));
        textInfo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textInfo.setForeground(new java.awt.Color(255, 255, 255));
        textInfo.setText(" ");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(textInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPublisher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCondition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(115, 115, 115)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(labelGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(71, 71, 71))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDvd)
                                    .addComponent(radioDvd)
                                    .addComponent(labelDirector1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboGenre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textDirector))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(labelBluRay)
                                        .addGap(85, 85, 85)
                                        .addComponent(label4K))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(radioBLuray)
                                        .addGap(69, 69, 69)
                                        .addComponent(radio4k)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(boxSteelCase)
                        .addGap(230, 230, 230)))
                .addGap(54, 54, 54))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTitle)
                        .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelGenre)
                        .addComponent(comboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrice)
                    .addComponent(textPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDirector1))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCondition)
                            .addComponent(comboCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDvd)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelBluRay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPublisher)
                                    .addComponent(textPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4K, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioDvd)
                                    .addComponent(radioBLuray)
                                    .addComponent(radio4k))))))
                .addGap(35, 35, 35)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxSteelCase)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelYear)
                        .addComponent(textYear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(textInfo)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void enterColor(JPanel temp) {
        temp.setBackground(new Color(202, 80, 16));
    }

    public void exitColor(JPanel temp) {
        temp.setBackground(new Color(60, 63, 66));
    }

    public void pressColor(JPanel temp) {
        temp.setBackground(new Color(255, 128, 0));
    }

    private void textPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPublisherActionPerformed

    private void textYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textYearActionPerformed

    private void textTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTitleActionPerformed

    private void textDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDirectorActionPerformed

    private void textPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPriceActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:

        if (textTitle.getText().isEmpty() || textPrice.getText().isEmpty() || textPublisher.getText().isEmpty() || textYear.getText().isEmpty() || textDirector.getText().isEmpty()) {
            textInfo.setText("Please fill the necessary fields!");
        } else {
            String title = textTitle.getText();
            double price = Double.parseDouble(textPrice.getText());
            String publisher = textPublisher.getText();
            String condition = comboCondition.getSelectedItem().toString();
            int year = Integer.parseInt(textYear.getText());

            String director = textDirector.getText();
            String genre = comboGenre.getSelectedItem().toString();
            String mediaType = "";
            if (radioDvd.isSelected()) {
                mediaType = "DVD";
            } else if (radioBLuray.isSelected()) {
                mediaType = "Bluray";
            } else if (radio4k.isSelected()) {
                mediaType = "4K";
            }
            Boolean steelCase = boxSteelCase.isSelected();

            Film f = new Film(director, mediaType, steelCase, genre, title, price, publisher, condition, year, 0);
            f.setWorth(f.worthCalculator());

            CollectiblesSys.addCollectible(f);

            textInfo.setText("Your Film is added to your collection!");
        }
    }//GEN-LAST:event_addButtonMouseClicked

    private void addButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseEntered
        // TODO add your handling code here:
        enterColor(addButton);
    }//GEN-LAST:event_addButtonMouseEntered

    private void addButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseExited
        // TODO add your handling code here:
        exitColor(addButton);
    }//GEN-LAST:event_addButtonMouseExited

    private void addButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMousePressed
        // TODO add your handling code here:
        pressColor(addButton);
    }//GEN-LAST:event_addButtonMousePressed

    private void addButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseReleased
        // TODO add your handling code here:
        enterColor(addButton);
    }//GEN-LAST:event_addButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addButton;
    private javax.swing.JPanel background;
    private javax.swing.JCheckBox boxSteelCase;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> comboCondition;
    private javax.swing.JComboBox<String> comboGenre;
    private javax.swing.JLabel label4K;
    private javax.swing.JLabel labelAdd;
    private javax.swing.JLabel labelBluRay;
    private javax.swing.JLabel labelCondition;
    private javax.swing.JLabel labelDirector1;
    private javax.swing.JLabel labelDvd;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelPublisher;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelYear;
    private javax.swing.JRadioButton radio4k;
    private javax.swing.JRadioButton radioBLuray;
    private javax.swing.JRadioButton radioDvd;
    private javax.swing.JTextField textDirector;
    private javax.swing.JLabel textInfo;
    private javax.swing.JTextField textPrice;
    private javax.swing.JTextField textPublisher;
    private javax.swing.JTextField textTitle;
    private javax.swing.JTextField textYear;
    // End of variables declaration//GEN-END:variables
}
