/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Ali and yusuf
 */
public class addSelectScreen extends javax.swing.JFrame {

    /**
     * Creates new form addSelectScreen
     */
    public addSelectScreen() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelComicBook = new javax.swing.JPanel();
        labelComicBook = new javax.swing.JLabel();
        panelFilm = new javax.swing.JPanel();
        labelFilm = new javax.swing.JLabel();
        panelFigure = new javax.swing.JPanel();
        labelFigure = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(37, 36, 35));

        panelComicBook.setBackground(new java.awt.Color(60, 63, 66));
        panelComicBook.setForeground(new java.awt.Color(60, 63, 65));
        panelComicBook.setPreferredSize(new java.awt.Dimension(200, 200));
        panelComicBook.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelComicBookMouseMoved(evt);
            }
        });
        panelComicBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelComicBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelComicBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelComicBookMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelComicBookMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelComicBookMouseReleased(evt);
            }
        });
        panelComicBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelComicBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_comic_book_96px.png"))); // NOI18N
        panelComicBook.add(labelComicBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        panelFilm.setBackground(new java.awt.Color(60, 63, 66));
        panelFilm.setForeground(new java.awt.Color(60, 63, 65));
        panelFilm.setPreferredSize(new java.awt.Dimension(200, 200));
        panelFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFilmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFilmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFilmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFilmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelFilmMouseReleased(evt);
            }
        });
        panelFilm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cinema_96px.png"))); // NOI18N
        panelFilm.add(labelFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        panelFigure.setBackground(new java.awt.Color(60, 63, 66));
        panelFigure.setForeground(new java.awt.Color(60, 63, 65));
        panelFigure.setPreferredSize(new java.awt.Dimension(200, 200));
        panelFigure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFigureMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFigureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFigureMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFigureMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelFigureMouseReleased(evt);
            }
        });
        panelFigure.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFigure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_statue_96px.png"))); // NOI18N
        panelFigure.add(labelFigure, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        labelName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText(" ");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panelComicBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(panelFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(panelFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelComicBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void enterColor(JPanel temp) {
        temp.setBackground(new Color(202, 80, 16));
    }

    public void exitColor(JPanel temp) {
        temp.setBackground(new Color(60, 63, 66));
    }

    public void pressColor(JPanel temp) {
        temp.setBackground(new Color(255, 128, 0));
    }
    private void panelComicBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicBookMouseEntered
        // TODO add your handling code here:
        labelName.setText("Comic Book");
        enterColor(panelComicBook);

    }//GEN-LAST:event_panelComicBookMouseEntered

    private void panelComicBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicBookMouseExited
        // TODO add your handling code here:
        labelName.setText("");
        exitColor(panelComicBook);

    }//GEN-LAST:event_panelComicBookMouseExited

    private void panelComicBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicBookMousePressed
        // TODO add your handling code here:
        pressColor(panelComicBook);
    }//GEN-LAST:event_panelComicBookMousePressed

    private void panelComicBookMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicBookMouseReleased
        // TODO add your handling code here:
        enterColor(panelComicBook);
    }//GEN-LAST:event_panelComicBookMouseReleased

    private void panelFilmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMouseEntered
        // TODO add your handling code here:
        labelName.setText("Film");
        enterColor(panelFilm);
    }//GEN-LAST:event_panelFilmMouseEntered

    private void panelFilmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMouseExited
        // TODO add your handling code here:
        labelName.setText("");
        exitColor(panelFilm);
    }//GEN-LAST:event_panelFilmMouseExited

    private void panelFilmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMousePressed
        // TODO add your handling code here:
        pressColor(panelFilm);
    }//GEN-LAST:event_panelFilmMousePressed

    private void panelFilmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMouseReleased
        // TODO add your handling code here:
        enterColor(panelFilm);
    }//GEN-LAST:event_panelFilmMouseReleased

    private void panelFigureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMouseEntered
        // TODO add your handling code here:
        labelName.setText("Figure");
        enterColor(panelFigure);
    }//GEN-LAST:event_panelFigureMouseEntered

    private void panelFigureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMouseExited
        // TODO add your handling code here:
        labelName.setText("");
        exitColor(panelFigure);
    }//GEN-LAST:event_panelFigureMouseExited

    private void panelFigureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMousePressed
        // TODO add your handling code here:
        pressColor(panelFigure);
    }//GEN-LAST:event_panelFigureMousePressed

    private void panelFigureMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMouseReleased
        // TODO add your handling code here:
        enterColor(panelFigure);
    }//GEN-LAST:event_panelFigureMouseReleased

    private void panelComicBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicBookMouseClicked
        // TODO add your handling code here:

        addComicBook c = new addComicBook();
        setVisible(false);
        c.setVisible(true);
        c.setTitle("Add Comic Book");
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_panelComicBookMouseClicked

    private void panelFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMouseClicked
        // TODO add your handling code here:
        addFilm f = new addFilm();
        setVisible(false);
        f.setVisible(true);
        f.setTitle("Add Film");
        f.setLocationRelativeTo(null);

    }//GEN-LAST:event_panelFilmMouseClicked

    private void panelFigureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMouseClicked
        // TODO add your handling code here:
        addFigure f = new addFigure();
        setVisible(false);
        f.setVisible(true);
        f.setTitle("Add Figure");
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_panelFigureMouseClicked

    private void panelComicBookMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicBookMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_panelComicBookMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSelectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSelectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSelectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSelectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSelectScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel labelComicBook;
    private javax.swing.JLabel labelFigure;
    private javax.swing.JLabel labelFilm;
    private javax.swing.JLabel labelName;
    private javax.swing.JPanel panelComicBook;
    private javax.swing.JPanel panelFigure;
    private javax.swing.JPanel panelFilm;
    // End of variables declaration//GEN-END:variables

}
