/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SystemAndMain.CollectiblesSys;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Ali and yusuf
 */
public class displayCollectibles extends javax.swing.JFrame {

    /**
     * Creates new form displayCollectibles
     */
    public displayCollectibles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelAll = new javax.swing.JPanel();
        labelAll = new javax.swing.JLabel();
        panelComic = new javax.swing.JPanel();
        labelComicBook = new javax.swing.JLabel();
        panelFilm = new javax.swing.JPanel();
        labelFilm = new javax.swing.JLabel();
        panelFigure = new javax.swing.JPanel();
        labelFigure = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(37, 36, 35));

        panelAll.setBackground(new java.awt.Color(60, 63, 66));
        panelAll.setForeground(new java.awt.Color(60, 63, 66));
        panelAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAllMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelAllMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelAllMouseReleased(evt);
            }
        });

        labelAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_database_64px.png"))); // NOI18N

        javax.swing.GroupLayout panelAllLayout = new javax.swing.GroupLayout(panelAll);
        panelAll.setLayout(panelAllLayout);
        panelAllLayout.setHorizontalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAllLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelAll)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelAllLayout.setVerticalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAllLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelComic.setBackground(new java.awt.Color(60, 63, 66));
        panelComic.setForeground(new java.awt.Color(60, 63, 66));
        panelComic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelComicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelComicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelComicMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelComicMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelComicMouseReleased(evt);
            }
        });

        labelComicBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_comic_book_64px.png"))); // NOI18N

        javax.swing.GroupLayout panelComicLayout = new javax.swing.GroupLayout(panelComic);
        panelComic.setLayout(panelComicLayout);
        panelComicLayout.setHorizontalGroup(
            panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComicLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelComicBook)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelComicLayout.setVerticalGroup(
            panelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComicLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelComicBook)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelFilm.setBackground(new java.awt.Color(60, 63, 66));
        panelFilm.setForeground(new java.awt.Color(60, 63, 66));
        panelFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFilmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFilmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFilmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFilmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelFilmMouseReleased(evt);
            }
        });

        labelFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cinema_64px_1.png"))); // NOI18N

        javax.swing.GroupLayout panelFilmLayout = new javax.swing.GroupLayout(panelFilm);
        panelFilm.setLayout(panelFilmLayout);
        panelFilmLayout.setHorizontalGroup(
            panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilmLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelFilm)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelFilmLayout.setVerticalGroup(
            panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilmLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelFilm)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelFigure.setBackground(new java.awt.Color(60, 63, 66));
        panelFigure.setForeground(new java.awt.Color(60, 63, 66));
        panelFigure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFigureMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFigureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFigureMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFigureMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelFigureMouseReleased(evt);
            }
        });

        labelFigure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_statue_64px.png"))); // NOI18N

        javax.swing.GroupLayout panelFigureLayout = new javax.swing.GroupLayout(panelFigure);
        panelFigure.setLayout(panelFigureLayout);
        panelFigureLayout.setHorizontalGroup(
            panelFigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFigureLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelFigure)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelFigureLayout.setVerticalGroup(
            panelFigureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFigureLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelFigure)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        textArea.setBackground(new java.awt.Color(60, 63, 66));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setRows(5);
        jScrollPane5.setViewportView(textArea);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(panelAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(panelComic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(panelFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(panelFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFigure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelComic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void enterColor(JPanel temp) {
        temp.setBackground(new Color(202, 80, 16));
    }

    public void exitColor(JPanel temp) {
        temp.setBackground(new Color(60, 63, 66));
    }

    public void pressColor(JPanel temp) {
        temp.setBackground(new Color(255, 128, 0));
    }

    private void panelAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseClicked
        // TODO add your handling code here:
        textArea.setText(CollectiblesSys.displayCollectibles());
    }//GEN-LAST:event_panelAllMouseClicked

    private void panelAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseEntered
        // TODO add your handling code here:
        enterColor(panelAll);
    }//GEN-LAST:event_panelAllMouseEntered

    private void panelAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseExited
        // TODO add your handling code here:
        exitColor(panelAll);
    }//GEN-LAST:event_panelAllMouseExited

    private void panelAllMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMousePressed
        // TODO add your handling code here:
        pressColor(panelAll);
    }//GEN-LAST:event_panelAllMousePressed

    private void panelAllMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseReleased
        // TODO add your handling code here:
        enterColor(panelAll);
    }//GEN-LAST:event_panelAllMouseReleased

    private void panelComicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicMouseClicked
        // TODO add your handling code here:
        textArea.setText(CollectiblesSys.displaySelectedCollectibles("comics"));

    }//GEN-LAST:event_panelComicMouseClicked

    private void panelComicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicMouseEntered
        // TODO add your handling code here:
        enterColor(panelComic);
    }//GEN-LAST:event_panelComicMouseEntered

    private void panelComicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicMouseExited
        // TODO add your handling code here:
        exitColor(panelComic);
    }//GEN-LAST:event_panelComicMouseExited

    private void panelComicMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicMousePressed
        // TODO add your handling code here:
        pressColor(panelComic);
    }//GEN-LAST:event_panelComicMousePressed

    private void panelComicMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComicMouseReleased
        // TODO add your handling code here:
        enterColor(panelComic);
    }//GEN-LAST:event_panelComicMouseReleased

    private void panelFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMouseClicked
        // TODO add your handling code here:
        textArea.setText(CollectiblesSys.displaySelectedCollectibles("films"));
    }//GEN-LAST:event_panelFilmMouseClicked

    private void panelFilmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMouseEntered
        // TODO add your handling code here:
        enterColor(panelFilm);
    }//GEN-LAST:event_panelFilmMouseEntered

    private void panelFilmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMouseExited
        // TODO add your handling code here:
        exitColor(panelFilm);
    }//GEN-LAST:event_panelFilmMouseExited

    private void panelFilmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMousePressed
        // TODO add your handling code here:
        pressColor(panelFilm);
    }//GEN-LAST:event_panelFilmMousePressed

    private void panelFilmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFilmMouseReleased
        // TODO add your handling code here:
        enterColor(panelFilm);
    }//GEN-LAST:event_panelFilmMouseReleased

    private void panelFigureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMouseClicked
        // TODO add your handling code here:
        textArea.setText(CollectiblesSys.displaySelectedCollectibles("figures"));
    }//GEN-LAST:event_panelFigureMouseClicked

    private void panelFigureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMouseEntered
        // TODO add your handling code here:
        enterColor(panelFigure);
    }//GEN-LAST:event_panelFigureMouseEntered

    private void panelFigureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMouseExited
        // TODO add your handling code here:
        exitColor(panelFigure);
    }//GEN-LAST:event_panelFigureMouseExited

    private void panelFigureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMousePressed
        // TODO add your handling code here:
        pressColor(panelFigure);
    }//GEN-LAST:event_panelFigureMousePressed

    private void panelFigureMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFigureMouseReleased
        // TODO add your handling code here:
        enterColor(panelFigure);
    }//GEN-LAST:event_panelFigureMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displayCollectibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displayCollectibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displayCollectibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displayCollectibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displayCollectibles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelAll;
    private javax.swing.JLabel labelComicBook;
    private javax.swing.JLabel labelFigure;
    private javax.swing.JLabel labelFilm;
    private javax.swing.JPanel panelAll;
    private javax.swing.JPanel panelComic;
    private javax.swing.JPanel panelFigure;
    private javax.swing.JPanel panelFilm;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
