package GUI;

import Inheritance.Collectibles;
import SystemAndMain.CollectiblesSys;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yusuf and ali eren
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Clip clip;

    public Main() {
        initComponents();
        showDate();
        showTime();
        music();
        setTitle("Collector's Database by Yusuf Çiftci and Ali Eren Çelebi");
        setLocationRelativeTo(null);

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }

    }

    public void showDate() {
        Date d = new Date();
        SimpleDateFormat s1 = new SimpleDateFormat("dd MMMMM yyyy");
        labelTime.setText(s1.format(d));
        labelTime.setForeground(Color.white);

    }

    public void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();

                SimpleDateFormat s2 = new SimpleDateFormat("k:mm:ss");
                labelHour.setText(s2.format(d));
                labelHour.setForeground(Color.white);
            }
        }).start();

    }

    public void music() {
        try {
            File musicPath = new File("music.wav");

            if (musicPath.exists()) {
                AudioInputStream audio = AudioSystem.getAudioInputStream(musicPath);
                clip = AudioSystem.getClip();
                clip.open(audio);
                clip.start();

                clip.loop(Clip.LOOP_CONTINUOUSLY);

            } else {
                System.out.println("ERROR");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        actionTitle = new javax.swing.JLabel();
        panelSide = new javax.swing.JPanel();
        labelAppName = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        labelCount = new javax.swing.JLabel();
        labelHour = new javax.swing.JLabel();
        labelItem = new javax.swing.JLabel();
        labelItemCount = new javax.swing.JLabel();
        labelTotalPrice = new javax.swing.JLabel();
        labelWorth = new javax.swing.JLabel();
        labelMute = new javax.swing.JLabel();
        panelAdd = new javax.swing.JPanel();
        labelAdd = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        labelSearch = new javax.swing.JLabel();
        panelDelete = new javax.swing.JPanel();
        labelDelete = new javax.swing.JLabel();
        panelDisplay = new javax.swing.JPanel();
        labelDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        background.setBackground(new java.awt.Color(37, 36, 35));
        background.setPreferredSize(new java.awt.Dimension(850, 600));

        actionTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        actionTitle.setForeground(new java.awt.Color(255, 255, 255));
        actionTitle.setText(" ");

        panelSide.setBackground(new java.awt.Color(202, 80, 16));
        panelSide.setPreferredSize(new java.awt.Dimension(250, 94));
        panelSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSideMouseEntered(evt);
            }
        });
        panelSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAppName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelAppName.setForeground(new java.awt.Color(255, 255, 255));
        labelAppName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cd_50px.png"))); // NOI18N
        labelAppName.setText("CD");
        panelSide.add(labelAppName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        labelTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_calendar_32px.png"))); // NOI18N
        labelTime.setText("time");
        panelSide.add(labelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        labelCount.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        labelCount.setForeground(new java.awt.Color(255, 255, 255));
        labelCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_money_bag_32px_1.png"))); // NOI18N
        panelSide.add(labelCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 100, 50));

        labelHour.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelHour.setText("time");
        panelSide.add(labelHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 100, -1));

        labelItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelItem.setForeground(new java.awt.Color(255, 255, 255));
        labelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_product_32px_1.png"))); // NOI18N
        labelItem.setText("TOTAL ITEMS: ");
        panelSide.add(labelItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        labelItemCount.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        labelItemCount.setForeground(new java.awt.Color(255, 255, 255));
        labelItemCount.setText("0");
        panelSide.add(labelItemCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        labelTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTotalPrice.setForeground(new java.awt.Color(255, 255, 255));
        labelTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalPrice.setText("0.0");
        panelSide.add(labelTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 190, 80));

        labelWorth.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelWorth.setForeground(new java.awt.Color(255, 255, 255));
        labelWorth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_expensive_price_32px.png"))); // NOI18N
        labelWorth.setText("TOTAL WORTH:");
        panelSide.add(labelWorth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        labelMute.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelMute.setForeground(new java.awt.Color(255, 255, 255));
        labelMute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_silent_32px.png"))); // NOI18N
        labelMute.setText("Press 'M' to Mute");
        panelSide.add(labelMute, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 250, -1));

        panelAdd.setBackground(new java.awt.Color(60, 63, 66));
        panelAdd.setForeground(new java.awt.Color(60, 63, 65));
        panelAdd.setPreferredSize(new java.awt.Dimension(200, 200));
        panelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelAddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelAddMouseReleased(evt);
            }
        });
        panelAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_96px.png"))); // NOI18N
        panelAdd.add(labelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        panelSearch.setBackground(new java.awt.Color(60, 63, 66));
        panelSearch.setForeground(new java.awt.Color(60, 63, 66));
        panelSearch.setPreferredSize(new java.awt.Dimension(200, 200));
        panelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelSearchMouseReleased(evt);
            }
        });
        panelSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_96px.png"))); // NOI18N
        panelSearch.add(labelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        panelDelete.setBackground(new java.awt.Color(60, 63, 66));
        panelDelete.setPreferredSize(new java.awt.Dimension(200, 200));
        panelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDeleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDeleteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelDeleteMouseReleased(evt);
            }
        });
        panelDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_trash_96px.png"))); // NOI18N
        panelDelete.add(labelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 57, -1, -1));

        panelDisplay.setBackground(new java.awt.Color(60, 63, 66));
        panelDisplay.setForeground(new java.awt.Color(60, 63, 65));
        panelDisplay.setPreferredSize(new java.awt.Dimension(200, 200));
        panelDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDisplayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDisplayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDisplayMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDisplayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelDisplayMouseReleased(evt);
            }
        });
        panelDisplay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_list_96px.png"))); // NOI18N
        panelDisplay.add(labelDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 50, -1, -1));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelSide, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(actionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionTitle)
                .addGap(35, 35, 35)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSideMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_panelSideMouseClicked

    private void panelSideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSideMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panelSideMouseEntered

    public void enterColor(JPanel temp) {
        temp.setBackground(new Color(202, 80, 16));
    }

    public void exitColor(JPanel temp) {
        temp.setBackground(new Color(60, 63, 66));
    }

    public void pressColor(JPanel temp) {
        temp.setBackground(new Color(255, 128, 0));
    }
    private void panelAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseEntered
        // TODO add your handling code here:

        enterColor(panelAdd);
        actionTitle.setText("Add Collectible");
    }//GEN-LAST:event_panelAddMouseEntered

    private void panelAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseExited
        // TODO add your handling code here:
        exitColor(panelAdd);
        actionTitle.setText(" ");
    }//GEN-LAST:event_panelAddMouseExited

    private void panelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseEntered
        // TODO add your handling code here:
        enterColor(panelSearch);
        actionTitle.setText("Search");
    }//GEN-LAST:event_panelSearchMouseEntered

    private void panelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseExited
        // TODO add your handling code here:
        exitColor(panelSearch);
        actionTitle.setText(" ");
    }//GEN-LAST:event_panelSearchMouseExited

    private void panelDisplayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDisplayMouseEntered
        // TODO add your handling code here:
        enterColor(panelDisplay);
        actionTitle.setText("Display");
    }//GEN-LAST:event_panelDisplayMouseEntered

    private void panelDisplayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDisplayMouseExited
        // TODO add your handling code here:
        exitColor(panelDisplay);
        actionTitle.setText(" ");
    }//GEN-LAST:event_panelDisplayMouseExited

    private void panelDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseEntered
        // TODO add your handling code here:
        enterColor(panelDelete);
        actionTitle.setText("Delete");
    }//GEN-LAST:event_panelDeleteMouseEntered

    private void panelDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseExited
        // TODO add your handling code here:
        exitColor(panelDelete);
        actionTitle.setText(" ");
    }//GEN-LAST:event_panelDeleteMouseExited

    private void panelAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMousePressed
        // TODO add your handling code here:
        pressColor(panelAdd);
    }//GEN-LAST:event_panelAddMousePressed

    private void panelAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseReleased
        // TODO add your handling code here:
        enterColor(panelAdd);
    }//GEN-LAST:event_panelAddMouseReleased

    private void panelSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMousePressed
        // TODO add your handling code here:
        pressColor(panelSearch);
    }//GEN-LAST:event_panelSearchMousePressed

    private void panelSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseReleased
        // TODO add your handling code here:
        enterColor(panelSearch);
    }//GEN-LAST:event_panelSearchMouseReleased

    private void panelDisplayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDisplayMousePressed
        // TODO add your handling code here:
        pressColor(panelDisplay);
    }//GEN-LAST:event_panelDisplayMousePressed

    private void panelDisplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDisplayMouseReleased
        // TODO add your handling code here:
        enterColor(panelDisplay);
    }//GEN-LAST:event_panelDisplayMouseReleased

    private void panelDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMousePressed
        // TODO add your handling code here:
        pressColor(panelDelete);
    }//GEN-LAST:event_panelDeleteMousePressed

    private void panelDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseReleased
        // TODO add your handling code here:
        enterColor(panelDelete);
    }//GEN-LAST:event_panelDeleteMouseReleased

    private void panelAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseClicked
        // TODO add your handling code here:
        addSelectScreen select = new addSelectScreen();
        select.setVisible(true);
        select.setTitle("Select Media");
        select.setLocationRelativeTo(null);
    }//GEN-LAST:event_panelAddMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:

        String count = Integer.toString(Collectibles.getTotalCount());
        labelItemCount.setText(count);

        String worth = Double.toString(CollectiblesSys.totalWorth);

        labelTotalPrice.setText(worth);
    }//GEN-LAST:event_formFocusGained

    private void panelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseClicked
        // TODO add your handling code here:

        removeCollectible r = new removeCollectible();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
        r.setTitle("Delete Collectible");
    }//GEN-LAST:event_panelDeleteMouseClicked

    private void panelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseClicked
        // TODO add your handling code here:
        searchCollectible sc = new searchCollectible();
        sc.setVisible(true);
        sc.setLocationRelativeTo(null);
        sc.setTitle("Search Collectible");
    }//GEN-LAST:event_panelSearchMouseClicked

    private void panelDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDisplayMouseClicked
        // TODO add your handling code here:
        displayCollectibles dc = new displayCollectibles();
        dc.setVisible(true);
        dc.setLocationRelativeTo(null);
        dc.setTitle("Collection Display");
    }//GEN-LAST:event_panelDisplayMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_M) {
            clip.stop();
            labelMute.setText("Press 'U' to Unmute");
        }
        if (key == KeyEvent.VK_U) {
            clip.start();
            labelMute.setText("Press 'M' to Mute");
        }
        if (key == KeyEvent.VK_ESCAPE) {

            System.exit(0);
        }

    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionTitle;
    private javax.swing.JPanel background;
    private javax.swing.JLabel labelAdd;
    private javax.swing.JLabel labelAppName;
    private javax.swing.JLabel labelCount;
    private javax.swing.JLabel labelDelete;
    private javax.swing.JLabel labelDisplay;
    private javax.swing.JLabel labelHour;
    private javax.swing.JLabel labelItem;
    public static javax.swing.JLabel labelItemCount;
    private javax.swing.JLabel labelMute;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel labelTime;
    public static javax.swing.JLabel labelTotalPrice;
    private javax.swing.JLabel labelWorth;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelDelete;
    private javax.swing.JPanel panelDisplay;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelSide;
    // End of variables declaration//GEN-END:variables
}
