/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Inheritance.Collectibles;
import SystemAndMain.CollectiblesSys;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ali and yusuf
 */
public class removeCollectible extends javax.swing.JFrame {

    /**
     * Creates new form removeCollectible
     */
    public removeCollectible() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg = new javax.swing.JDialog();
        bg = new javax.swing.JPanel();
        warning = new javax.swing.JLabel();
        panelDelete = new javax.swing.JPanel();
        labelDelete = new javax.swing.JLabel();
        panelCancel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textDeleteSearch = new javax.swing.JTextField();
        labelRemove = new javax.swing.JLabel();
        labelSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        msg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg.setBackground(new java.awt.Color(37, 36, 35));

        warning.setBackground(new java.awt.Color(255, 255, 255));
        warning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 255, 255));
        warning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_nothing_found_32px.png"))); // NOI18N
        warning.setText("Are you sure you wan't to delete this item?");

        panelDelete.setBackground(new java.awt.Color(60, 63, 66));
        panelDelete.setForeground(new java.awt.Color(60, 63, 66));
        panelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDeleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDeleteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelDeleteMouseReleased(evt);
            }
        });

        labelDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelDelete.setForeground(new java.awt.Color(255, 255, 255));
        labelDelete.setText("DELETE");

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDelete)
                .addContainerGap())
        );

        panelCancel.setBackground(new java.awt.Color(60, 63, 66));
        panelCancel.setForeground(new java.awt.Color(60, 63, 66));
        panelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelCancelMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANCEL");

        javax.swing.GroupLayout panelCancelLayout = new javax.swing.GroupLayout(panelCancel);
        panelCancel.setLayout(panelCancelLayout);
        panelCancelLayout.setHorizontalGroup(
            panelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCancelLayout.setVerticalGroup(
            panelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(panelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(panelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(warning)
                .addGap(52, 52, 52))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(warning)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout msgLayout = new javax.swing.GroupLayout(msg.getContentPane());
        msg.getContentPane().setLayout(msgLayout);
        msgLayout.setHorizontalGroup(
            msgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        msgLayout.setVerticalGroup(
            msgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 36, 35));

        textDeleteSearch.setBackground(new java.awt.Color(60, 63, 66));
        textDeleteSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textDeleteSearch.setForeground(new java.awt.Color(255, 255, 255));
        textDeleteSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 66), 2));
        textDeleteSearch.setCaretColor(new java.awt.Color(202, 80, 16));
        textDeleteSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textDeleteSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDeleteSearchActionPerformed(evt);
            }
        });

        labelRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelRemove.setForeground(new java.awt.Color(255, 255, 255));
        labelRemove.setText("Enter your Collectible's name to remove from CD ");

        labelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_clear_search_32px.png"))); // NOI18N

        textArea.setBackground(new java.awt.Color(60, 63, 66));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setRows(5);
        textArea.setToolTipText("");
        textArea.setBorder(null);
        textArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textArea.setFocusable(false);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(labelRemove)
                    .addComponent(textDeleteSearch)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelRemove)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDeleteSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void enterColor(JPanel temp) {
        temp.setBackground(new Color(202, 80, 16));
    }

    public void exitColor(JPanel temp) {
        temp.setBackground(new Color(60, 63, 66));
    }

    public void pressColor(JPanel temp) {
        temp.setBackground(new Color(255, 128, 0));
    }
    private void textDeleteSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDeleteSearchActionPerformed
        // TODO add your handling code here:
        Collectibles c = CollectiblesSys.searchCollectible(textDeleteSearch.getText());

        if (c != null) {
            textArea.setText(c.toString());

            msg.setVisible(true);
            msg.setTitle("Warning!");
            msg.setSize(398, 160);
            msg.setLocationRelativeTo(null);
        } else {
            textArea.setText("Can't found it");
            warning w = new warning();
            w.setVisible(true);
            w.setTitle("Warning!");
            w.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_textDeleteSearchActionPerformed

    private void panelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseClicked
        // TODO add your handling code here:
        CollectiblesSys.removeCollectible(textDeleteSearch.getText());
        msg.setVisible(false);
        textArea.setText("Your item is deleted");
    }//GEN-LAST:event_panelDeleteMouseClicked

    private void panelDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseEntered
        // TODO add your handling code here:
        enterColor(panelDelete);
    }//GEN-LAST:event_panelDeleteMouseEntered

    private void panelDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseExited
        // TODO add your handling code here:
        exitColor(panelDelete);
    }//GEN-LAST:event_panelDeleteMouseExited

    private void panelDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMousePressed
        // TODO add your handling code here:
        pressColor(panelDelete);
    }//GEN-LAST:event_panelDeleteMousePressed

    private void panelDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseReleased
        // TODO add your handling code here:
        enterColor(panelDelete);
    }//GEN-LAST:event_panelDeleteMouseReleased

    private void panelCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelMouseClicked
        // TODO add your handling code here:
        msg.setVisible(false);
    }//GEN-LAST:event_panelCancelMouseClicked

    private void panelCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelMouseEntered
        // TODO add your handling code here:
        enterColor(panelCancel);

    }//GEN-LAST:event_panelCancelMouseEntered

    private void panelCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelMouseExited
        // TODO add your handling code here:
        exitColor(panelCancel);
    }//GEN-LAST:event_panelCancelMouseExited

    private void panelCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelMousePressed
        // TODO add your handling code here:
        pressColor(panelCancel);
    }//GEN-LAST:event_panelCancelMousePressed

    private void panelCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelMouseReleased
        // TODO add your handling code here:
        enterColor(panelCancel);
    }//GEN-LAST:event_panelCancelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeCollectible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeCollectible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeCollectible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeCollectible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeCollectible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDelete;
    private javax.swing.JLabel labelRemove;
    private javax.swing.JLabel labelSearch;
    public javax.swing.JDialog msg;
    private javax.swing.JPanel panelCancel;
    public javax.swing.JPanel panelDelete;
    private javax.swing.JTextArea textArea;
    public javax.swing.JTextField textDeleteSearch;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
