/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Inheritance.Collectibles;
import SystemAndMain.CollectiblesSys;

/**
 *
 * @author yusuf and ali eren
 */
public class searchCollectible extends javax.swing.JFrame {

    /**
     * Creates new form searchCollectible
     */
    public searchCollectible() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        textDeleteSearch = new javax.swing.JTextField();
        labelSearchTitle = new javax.swing.JLabel();
        labelSearch = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        textSearch = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(37, 36, 35));
        background.setToolTipText("");

        textDeleteSearch.setBackground(new java.awt.Color(60, 63, 66));
        textDeleteSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textDeleteSearch.setForeground(new java.awt.Color(255, 255, 255));
        textDeleteSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 66), 2));
        textDeleteSearch.setCaretColor(new java.awt.Color(202, 80, 16));
        textDeleteSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textDeleteSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDeleteSearchActionPerformed(evt);
            }
        });

        labelSearchTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelSearchTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelSearchTitle.setText("Enter your Collectible's name to SEARCH");

        labelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_32px_1.png"))); // NOI18N

        textSearch.setBackground(new java.awt.Color(60, 63, 66));
        textSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 36, 35)));
        textSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textSearch.setForeground(new java.awt.Color(255, 255, 255));
        textSearch.setCaretColor(new java.awt.Color(255, 255, 255));
        textSearch.setFocusable(false);
        textSearch.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(textSearch);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(labelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(labelSearchTitle)
                            .addComponent(textDeleteSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelSearchTitle)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDeleteSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDeleteSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDeleteSearchActionPerformed
        // TODO add your handling code here:
        Collectibles c = CollectiblesSys.searchCollectible(textDeleteSearch.getText());

        if (c != null) {
            textSearch.setText(c.toString());

            //msg.setVisible(true);
            //msg.setTitle("Warning!");
            //msg.setSize(398, 160);
            //msg.setLocationRelativeTo(null);
        } else {
            // jFormattedTextField1.setText("Can't found it");
            warning w = new warning();
            w.setVisible(true);
            w.setTitle("Warning!");
            w.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_textDeleteSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchCollectible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchCollectible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchCollectible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchCollectible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchCollectible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel labelSearchTitle;
    public javax.swing.JTextField textDeleteSearch;
    private javax.swing.JTextPane textSearch;
    // End of variables declaration//GEN-END:variables
}
