/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Ali and yusuf
 */
public class warning extends javax.swing.JFrame {

    /**
     * Creates new form warning
     */
    public warning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        warning = new javax.swing.JLabel();
        panelOk = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(37, 36, 35));

        warning.setBackground(new java.awt.Color(255, 255, 255));
        warning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 255, 255));
        warning.setText("You don't have that item in your Collection");

        panelOk.setBackground(new java.awt.Color(60, 63, 66));
        panelOk.setForeground(new java.awt.Color(60, 63, 66));
        panelOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelOkMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_sad_32px.png"))); // NOI18N
        jLabel1.setText("OK");

        javax.swing.GroupLayout panelOkLayout = new javax.swing.GroupLayout(panelOk);
        panelOk.setLayout(panelOkLayout);
        panelOkLayout.setHorizontalGroup(
            panelOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOkLayout.setVerticalGroup(
            panelOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(warning)
                .addGap(16, 16, 16))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(panelOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(warning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(panelOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void enterColor(JPanel temp) {
        temp.setBackground(new Color(202, 80, 16));
    }

    public void exitColor(JPanel temp) {
        temp.setBackground(new Color(60, 63, 66));
    }

    public void pressColor(JPanel temp) {
        temp.setBackground(new Color(255, 128, 0));
    }
    private void panelOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOkMouseEntered
        // TODO add your handling code here:
        enterColor(panelOk);
    }//GEN-LAST:event_panelOkMouseEntered

    private void panelOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOkMouseExited
        // TODO add your handling code here:
        exitColor(panelOk);
    }//GEN-LAST:event_panelOkMouseExited

    private void panelOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOkMousePressed
        // TODO add your handling code here:
        pressColor(panelOk);
    }//GEN-LAST:event_panelOkMousePressed

    private void panelOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOkMouseReleased
        // TODO add your handling code here:
        enterColor(panelOk);
    }//GEN-LAST:event_panelOkMouseReleased

    private void panelOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOkMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_panelOkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new warning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelOk;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
